// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using rinha_backend.Context;

#nullable disable

namespace rinha_backend.Migrations
{
    [DbContext(typeof(RinhaContext))]
    partial class RinhaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("rinha_backend.Entity.Pessoa", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apelido")
                        .HasColumnType("text")
                        .HasColumnName("apelido");

                    b.Property<string>("DbStack")
                        .HasColumnType("text")
                        .HasColumnName("stack");

                    b.Property<string>("Nascimento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nascimento");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Apelido")
                        .IsUnique();

                    b.ToTable("pessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
